version: "3.8"
services:
    node01:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
        container_name: node01
        logging:
            driver: none
        environment:
            - node.name=node01
            - cluster.name=es-cluster-7
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - es-data01:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - es-network

    kibana:
        image: docker.elastic.co/kibana/kibana:7.14.0
        container_name: kibana
        logging:
            driver: none
        environment:
            ELASTICSEARCH_HOSTS: http://node01:9200
        ports:
            - 5601:5601
        networks:
            - es-network
        depends_on:
            - node01

    # backend:
    #     build: ./backend
    #     volumes:
    #         - .:/backend
    #     ports:
    #         - "3000:3000"
    #     container_name: backend
    #     logging:
    #         driver: none
    #     restart: always
    #     depends_on:
    #         - elastic
    #         - kibana
    #     networks:
    #         - es-network
    #     links:
    #         - elastic
    #         - kibana
volumes:
    es-data01:
        driver: local

networks:
    es-network:
        driver: bridge
